name: InnoQuiz CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: |
        cd inno_quiz
        poetry install
    
    - name: Lint with flake8
      run: |
        cd inno_quiz
        poetry run flake8 backend
    
    - name: Test with pytest and check coverage
      run: |
        cd inno_quiz/backend
        # Create a dummy .env file for tests
        cp .env.example .env
        
        # Run tests excluding external API tests with minimum coverage of 60%
        poetry run pytest -m "not external" --cov=backend --cov-report=term --cov-fail-under=60 