name: InnoQuiz CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: |
        cd inno_quiz
        poetry install
    
    - name: Lint with flake8
      run: |
        cd inno_quiz
        poetry run flake8 backend
    
    - name: Test with pytest and check coverage
      run: |
        cd inno_quiz/backend
        # Create a dummy .env file for tests
        cp .env.example .env
        
        # Run all tests with coverage
        poetry run pytest --cov=. --cov-report=term --cov-fail-under=60 
    
    - name: Initialize database for load testing
      run: |
        cd inno_quiz/backend
        # Make sure the database is initialized with tables
        if [ -f init_db.py ]; then
          poetry run python init_db.py
        fi
    
    - name: Start backend server for load testing
      run: |
        cd inno_quiz/backend
        # Start the server in the background
        poetry run uvicorn main:app --host 0.0.0.0 --port 8000 &
        # Wait for the server to start
        sleep 5
      
    - name: Run load tests
      run: |
        cd inno_quiz/backend
        # Run load tests in headless mode for a short duration
        poetry run locust --headless -u 10 -r 1 --run-time 30s --host http://localhost:8000 -f locustfile.py --exit-code-on-error 0 